"""Provision a Cognito advisory principal and sync advisory data to its real sub.

This is the onboarding/provisioning layer for the advisory flow. It keeps the
runtime contract unchanged:

    Cognito sub == backend user_id == orchestrator actor_id == specialist user_id

The script does not introduce any runtime remap. Instead, it creates a Cognito
user first, reads the actual `sub` generated by Cognito, then provisions the
Supabase advisory dataset under that exact user id.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import os
import secrets
import string
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Sequence

import boto3
from botocore.exceptions import ClientError

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend" / "scripts"))

from sync_supabase_user_dataset import load_env_file, sync_user_dataset  # noqa: E402


UTC = timezone.utc


def _utc_now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _load_env_files(paths: Sequence[str]) -> None:
    for path_str in paths:
        path = Path(path_str)
        if path.exists():
            load_env_file(path)


def _resolve(name: str, explicit: str | None = None, default: str = "") -> str:
    if explicit is not None and str(explicit).strip():
        return str(explicit).strip()
    return str(os.getenv(name) or default).strip()


def _secret_hash(username: str, client_id: str, client_secret: str) -> str:
    msg = (username + client_id).encode("utf-8")
    key = client_secret.encode("utf-8")
    digest = hmac.new(key, msg, hashlib.sha256).digest()
    return base64.b64encode(digest).decode()


def _generate_password(length: int = 20) -> str:
    if length < 16:
        raise ValueError("Password length must be at least 16.")
    alphabet = string.ascii_letters + string.digits
    punctuation = "!@#$%^&*()-_=+"
    chars = [
        secrets.choice(string.ascii_lowercase),
        secrets.choice(string.ascii_uppercase),
        secrets.choice(string.digits),
        secrets.choice(punctuation),
    ]
    pool = alphabet + punctuation
    while len(chars) < length:
        chars.append(secrets.choice(pool))
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def _cognito_session(profile: str | None, region: str):
    if profile:
        return boto3.Session(profile_name=profile, region_name=region)
    return boto3.Session(region_name=region)


def _create_cognito_user(
    *,
    profile: str | None,
    region: str,
    user_pool_id: str,
    email: str,
    password: str,
) -> Dict[str, Any]:
    session = _cognito_session(profile, region)
    admin = session.client("cognito-idp")

    response = admin.admin_create_user(
        UserPoolId=user_pool_id,
        Username=email,
        UserAttributes=[
            {"Name": "email", "Value": email},
            {"Name": "email_verified", "Value": "true"},
        ],
        MessageAction="SUPPRESS",
    )
    cognito_username = str(response["User"]["Username"])

    admin.admin_set_user_password(
        UserPoolId=user_pool_id,
        Username=cognito_username,
        Password=password,
        Permanent=True,
    )

    user_info = admin.admin_get_user(UserPoolId=user_pool_id, Username=cognito_username)
    attrs = {item["Name"]: item["Value"] for item in user_info.get("UserAttributes", [])}
    sub = str(attrs.get("sub") or cognito_username).strip()
    if not sub:
        raise RuntimeError("Created Cognito user did not expose a valid sub.")

    return {
        "email": email,
        "username": cognito_username,
        "sub": sub,
        "status": str(user_info.get("UserStatus") or ""),
        "enabled": True,
    }


def _validate_public_auth(
    *,
    region: str,
    client_id: str,
    client_secret: str,
    email: str,
    password: str,
) -> Dict[str, Any]:
    public = boto3.client("cognito-idp", region_name=region)
    auth_params = {"USERNAME": email, "PASSWORD": password}
    if client_secret:
        auth_params["SECRET_HASH"] = _secret_hash(email, client_id, client_secret)
    response = public.initiate_auth(
        ClientId=client_id,
        AuthFlow="USER_PASSWORD_AUTH",
        AuthParameters=auth_params,
    )
    access_token = str(response["AuthenticationResult"]["AccessToken"])
    payload = access_token.split(".")[1]
    payload += "=" * (-len(payload) % 4)
    claims = json.loads(base64.urlsafe_b64decode(payload))
    return {
        "access_token": access_token,
        "claims": claims,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a Cognito advisory principal, then sync advisory data to its generated sub.",
    )
    parser.add_argument("--source-user-id", required=True)
    parser.add_argument("--email", required=True)
    parser.add_argument("--password", default="")
    parser.add_argument("--aws-profile", default="")
    parser.add_argument("--aws-region", default="")
    parser.add_argument("--cognito-user-pool-id", default="")
    parser.add_argument("--cognito-client-id", default="")
    parser.add_argument("--cognito-client-secret", default="")
    parser.add_argument("--env-file", action="append", default=[])
    parser.add_argument("--report-path", default="")
    parser.add_argument("--sync-report-path", default="")
    parser.add_argument("--token-env-path", default="")
    parser.add_argument("--timeout", type=int, default=45)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    _load_env_files(args.env_file)

    region = _resolve("AWS_REGION", args.aws_region, default="us-east-1")
    user_pool_id = _resolve("COGNITO_USER_POOL_ID", args.cognito_user_pool_id)
    client_id = _resolve("COGNITO_CLIENT_ID", args.cognito_client_id)
    client_secret = _resolve("COGNITO_CLIENT_SECRET", args.cognito_client_secret)
    supabase_url = _resolve("SUPABASE_URL")
    service_role_key = _resolve("SUPABASE_SERVICE_ROLE_KEY")
    profile = str(args.aws_profile or "").strip() or None

    if not user_pool_id:
        raise SystemExit("COGNITO_USER_POOL_ID is required.")
    if not client_id:
        raise SystemExit("COGNITO_CLIENT_ID is required.")
    if not supabase_url or not service_role_key:
        raise SystemExit("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.")

    password = str(args.password or "").strip() or _generate_password()
    cognito_user = _create_cognito_user(
        profile=profile,
        region=region,
        user_pool_id=user_pool_id,
        email=str(args.email).strip(),
        password=password,
    )

    auth_probe = _validate_public_auth(
        region=region,
        client_id=client_id,
        client_secret=client_secret,
        email=cognito_user["email"],
        password=password,
    )
    claims = auth_probe["claims"]
    token_sub = str(claims.get("sub") or "").strip()
    if token_sub != cognito_user["sub"]:
        raise RuntimeError("Public auth token sub does not match the created Cognito user sub.")

    sync_report_path = (
        Path(args.sync_report_path)
        if args.sync_report_path
        else REPO_ROOT / "backend" / "tmp" / f"advisory_sync_{token_sub}.json"
    )
    sync_report = sync_user_dataset(
        source_user_id=str(args.source_user_id).strip(),
        target_user_id=token_sub,
        target_email=cognito_user["email"],
        supabase_url=supabase_url,
        service_role_key=service_role_key,
        timeout=int(args.timeout),
        report_path=sync_report_path,
    )

    token_env_path = (
        Path(args.token_env_path)
        if args.token_env_path
        else REPO_ROOT / "backend" / "tmp" / f"advisory_principal_{token_sub}.env"
    )
    token_env_path.parent.mkdir(parents=True, exist_ok=True)
    token_env_path.write_text(
        "\n".join(
            [
                f"AWS_REGION={region}",
                f"COGNITO_CLIENT_ID={client_id}",
                f"COGNITO_CLIENT_SECRET={client_secret}",
                f"COGNITO_USERNAME={cognito_user['email']}",
                f"COGNITO_PASSWORD={password}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    manifest = {
        "created_at": _utc_now_iso(),
        "source_user_id": str(args.source_user_id).strip(),
        "advisory_principal": {
            "email": cognito_user["email"],
            "username": cognito_user["username"],
            "sub": cognito_user["sub"],
            "user_status": cognito_user["status"],
        },
        "cognito": {
            "region": region,
            "user_pool_id": user_pool_id,
            "client_id": client_id,
        },
        "sync_report_path": str(sync_report_path),
        "token_env_path": str(token_env_path),
        "verified_counts": sync_report.get("verified_counts", {}),
        "transaction_range": sync_report.get("transaction_range", {}),
    }
    report_path = (
        Path(args.report_path)
        if args.report_path
        else REPO_ROOT / "backend" / "tmp" / f"advisory_principal_manifest_{token_sub}.json"
    )
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    print(str(report_path))
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
